$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: reasoning-paper
endpoint_name: mc-reasoning
model:
  path: models/
code_configuration:
  code: scoring/
  scoring_script: score.py
environment: 
  conda_file: environment/environment.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
instance_type: STANDARD_E4S_V3
instance_count: 1
request_settings:
  request_timeout_ms: 180000
